### ISSUE TITLE
正式环境多worker下登录状态紊乱

### ISSUE THREAD

**Issue by ruix156** [staugur/picbed#10]
使用docker-compose搭建好后，没法打开站点管理，其他的都是正常的。站点管理显示
404
-- Not Found --
返回首页

**Comment by staugur** [comment]
管理员用户？

**Comment by ruix156** [comment]
> 管理员用户？

就是这个命令啊
docker-compose exec webapp flask sa create -u 管理员账号 -p 密码 --isAdmin

**Comment by staugur** [comment]
站点管理403说明没权限，404说明没登录。
提示这个的时候状态是登录的吗?
是不是启动了2个及以上进程?是的话，设置下固定的secretkey再试试

**Comment by ruix156** [comment]
直接修改src/config.py然后再
docker-compose up -d ?
我发现好像就是登录cookies的原因，
有时候能打开，但是打开其他功能就又让登录了
Ps看了确实是两个进程

**Comment by staugur** [comment]
那就是了，先固定secretkey，设置环境变量，或者.cfg文件写，再up下

**Comment by staugur** [comment]
这个问题确实一直存在，最近才意识到，已经在dev最新代码中修改，以往版本可以通过设置SecretKey(环境变量picbed_secretkey)解决

**Comment by ruix156** [comment]
那我可以把整个目录删了，重新git,然后up了吧？

**Comment by staugur** [comment]
git clone -b dev https://github.com/staugur/picbed

**Comment by ruix156** [comment]
试了几遍都没问题了，谢谢大佬了
